# Copyright (c) 2015 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- get_url: url=http://archive.cloudera.com/cm5/{{ ansible_os_family | lower }}/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/cm/cloudera-manager.repo
           dest=/etc/yum.repos.d/
  when: ansible_os_family == "RedHat"
  become: yes

- get_url: url=http://archive.cloudera.com/cm5/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/amd64/cm/cloudera.list
           dest=/etc/apt/sources.list.d/
  when: ansible_os_family == "Debian"
  become: yes

- apt: update_cache=yes
  when: ansible_os_family == "Debian"
  become: yes

# vi:et:sw=2 ts=2 sts=2 ft=ansible
