# Copyright (c) 2015 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- set_fact: filename={{ bosh_workspace }}/docker-broker-bosh-lite.yml

- template: src=docker-broker-bosh-lite.yml.j2 dest={{ filename }}
            validate='python -c "import yaml; yaml.load(file('%s', 'r'))"'
  notify:
    - bosh deployment
    - bosh deploy

- meta: flush_handlers

# https://github.com/cf-platform-eng/docker-boshrelease#cloud-foundry-security-groups
- copy: src=everything.json dest=/tmp/everything.json
  register: everything_json
  notify:
    - cloud foundry security groups

- uri: url=http://cf-containers-broker.{{ cf_domain }}/v2/catalog
       user=containers password=containers force_basic_auth=yes
  register: cf_containers_broker_v2_catalog_result
  until: cf_containers_broker_v2_catalog_result.status == 200
  retries: 15
  delay: 60

# vi:et:sw=2 ts=2 sts=2 ft=ansible
