# Copyright (c) 2015 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- hosts: bosh-lite
  vars:
    grub_cmdline_linux: cgroup_enable=memory swapaccount=1 max_loop=255
  handlers:
    - name: update-grub
      shell: update-grub
      become: yes
    # https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back
    - name: restart machine
      command: shutdown -r now "Ansible updates triggered"
      async: 0
      poll: 0
      ignore_errors: true
      become: yes
  pre_tasks:
    - lineinfile: dest=/etc/cloud/cloud.cfg regexp="^ - (scripts-user)$"
                  line=" - [ \1, always ]" backrefs=yes
      become: yes
  tasks:
    - lineinfile: dest=/etc/default/grub regexp="^GRUB_CMDLINE_LINUX=\"\"$"
                  line="GRUB_CMDLINE_LINUX=\"{{ grub_cmdline_linux }}\""
                  backrefs=yes
      notify:
        - update-grub
        - restart machine
      become: yes
    - meta: flush_handlers

- hosts: bosh-lite
  roles:
    - common
    - bosh_provisioner
  post_tasks:
    - shell: iptables -S
      changed_when: False
      register: iptables_result
      become: yes
    - shell: iptables {{ item }}
      with_items:
        - -A w--forward -d 10.244.0.34/32 -p tcp -m state --state NEW,RELATED,ESTABLISHED -m tcp --dport 80 -j ACCEPT
        - -A w--forward -d 10.244.0.34/32 -p tcp -m state --state NEW,RELATED,ESTABLISHED -m tcp --dport 443 -j ACCEPT
        - -A w--forward -d 10.244.0.34/32 -p tcp -m state --state NEW,RELATED,ESTABLISHED -m tcp --dport 4443 -j ACCEPT
      when: not iptables_result.stdout | search(item)
      become: yes
    - shell: iptables -t nat -S
      changed_when: False
      register: iptables_result
      become: yes
    - shell: iptables -t nat {{ item }}
      with_items:
        - -A w--postrouting -s 10.244.0.34/32 -p tcp -m tcp --sport 80 -j SNAT --to-source {{ ansible_default_ipv4['address'] }}
        - -A w--postrouting -s 10.244.0.34/32 -p tcp -m tcp --sport 443 -j SNAT --to-source {{ ansible_default_ipv4['address'] }}
        - -A w--postrouting -s 10.244.0.34/32 -p tcp -m tcp --sport 4443 -j SNAT --to-source {{ ansible_default_ipv4['address'] }}
        - -A w--prerouting -d {{ ansible_default_ipv4['address'] }}/32 -p tcp -m tcp --dport 80 -j DNAT --to-destination 10.244.0.34:80
        - -A w--prerouting -d {{ ansible_default_ipv4['address'] }}/32 -p tcp -m tcp --dport 443 -j DNAT --to-destination 10.244.0.34:443
        - -A w--prerouting -d {{ ansible_default_ipv4['address'] }}/32 -p tcp -m tcp --dport 4443 -j DNAT --to-destination 10.244.0.34:4443
      when: not iptables_result.stdout | search(item)
      become: yes

# vi:et:sw=2 ts=2 sts=2 ft=ansible
